Chnage bitnami/mariadb:10.3 to mariadb:10.0.33
If use upper MariaDB 10.1 , get error when run "python manage.py migrate".

Like below.

MySQLdb._exceptions.OperationalError: (1025, 'Error on rename of \'./django/auth_permission\' to \'./django/#sql2-1-2\' (errno: -1 "Internal error < 0 (Not system error)")')

The above exception was the direct cause of the following exception: